[build]
  command = "npm run build"
  publish = "dist"

# Single-page application logic: redirects all requests to index.html (optional but good natively)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
